### ISSUE TITLE
Apply with schema & templates produces "Provider produced inconsistent result after apply" error

### ISSUE THREAD

**Issue by aj-cruz** [terraform-providers/terraform-provider-mso#32]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.28
+ provider.mso (unversioned)

### MSO version

2.2(4e)

### APIC version and APIC Platform for Site Level Resources

4.2(3q) on-prem (simulator)

### Affected Resource(s)

mso_schema
mso_schema_template

### Terraform Configuration Files

```
 provider "mso" {
    username = "python"
    password = "ajlab.local1"
    url      = "https://<url>"
    insecure = true
}

data "mso_user" "python" {
  username = "python"
}
data "mso_user" "admin" {
  username = "admin"
}

resource "mso_site" "Philadelphia" {
  name = "Philadelphia"
  username = "admin"
  password = "ajlab.local"
  apic_site_id = "1"
  urls = [ "https://192.168.253.17" ]
}

resource "mso_site" "RioDeJaneiro" {
  name = "RioDeJaneiro"
  username = "admin"
  password = "ajlab.local"
  apic_site_id = "2"
  urls = [ "https://192.168.253.18" ]
}

resource "mso_tenant" "CompanyXYZ-Prod" {
  name = "CompanyXYZ-Prod"
  display_name = "CompanyXYZ-Prod"
  site_associations{
    site_id = mso_site.Philadelphia.id
    }
  site_associations{
    site_id = mso_site.RioDeJaneiro.id
    }
  user_associations{
    user_id = data.mso_user.python.id
    }
  user_associations{
    user_id = data.mso_user.admin.id
    }
}

resource "mso_schema" "CompanyXYZ-Schema" {
  name          = "CompanyXYZ-Schema"
  template_name = "Shared-Template"
  tenant_id     = mso_tenant.CompanyXYZ-Prod.id
}

resource "mso_schema_template" "Philly-Template" {
  schema_id = mso_schema.CompanyXYZ-Schema.id
  name = "Philly-Template"
  display_name = "Philly-Template"
  tenant_id = mso_tenant.CompanyXYZ-Prod.id
}

resource "mso_schema_template" "Rio-Template" {
  schema_id = mso_schema.CompanyXYZ-Schema.id
  name = "Rio-Template"
  display_name = "Rio-Template"
  tenant_id = mso_tenant.CompanyXYZ-Prod.id
}
```

### Debug Output

[https://gist.github.com/aj-cruz/27b19c63985e9ac30136dc7b103884a6](url)

### Expected Behavior

Creation of schema and three templates (Shared, Philly, & Rio).

### Actual Behavior

Schema and two templates created (Philly generated an error):
```
Error: Provider produced inconsistent result after apply

When applying changes to mso_schema_template.Philly-Template, provider
"registry.terraform.io/-/mso" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. Added mso_schema & mso_schema_template resources (others were already created).
2. terraform apply

### Important Factoids

I noticed if I run it again the Philly template is created no problem.
Then I added four mso_schema_template_anp resources and the same thing happened. One ANP was created and then the same error was generated three times. I did terraform apply again and the second ANP was created followed by the same error two times. I ran terraform two more times to get all four ANPs created, then the error went away.

### References

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

* #0000

**Comment by nkatarmal-crest** [comment]
@aj-cruz Can you try running your Terraform configuration with a --parallelism=1 flag? I am seeing that Create Operation was successful but MSO was not able to return the template in get call.

**Comment by aj-cruz** [comment]
@nkatarmal-crest That worked. I realized I needed some depends_on parameters in there, once I got those in it runs clean with the parallelism=1, but still not without. Thanks.

**Comment by nkatarmal-crest** [comment]
@aj-cruz Can you clean your plan and MSO setup and run the hashicorp release version of the MSO provider. I.e v0.1.1? 



EDIT:

Also if you can clear you logs in the gist and put the new one with the Hashicorp released binary. That would be helpful to troubleshoot the issue better.

**Comment by aj-cruz** [comment]
@nkatarmal-crest Cleaned the plan, wiped the MSO setup, and deleted the compiled MSO provider from the plugins directory so that it pulls in the hashicorp release version. It ran clean and created all three templates.
I have updated the gist.

**Comment by nkatarmal-crest** [comment]
@aj-cruz Are you still facing this issue or we can mark this one as closed?
